export const surpriseMePrompts = [
    'an armchair in the shape of an avocado',
    'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
    'teddy bears shopping for groceries in Japan, ukiyo-e',
    'an oil painting by Matisse of a humanoid robot playing chess',
    'panda mad scientist mixing sparkling chemicals, digital art',
    "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'a stained glass window depicting a hamburger and french fries',
    'a pencil and watercolor drawing of a bright city in the future with flying cars',
    'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
    'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder on a black background',
    'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
    'A photo of a white fur monster standing in a purple room',
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    'A Samurai riding a Horse on Mars, lomography.',
    'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
    'A realistic photograph of a young woman with blue eyes and blonde hair',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A BBQ that is alive, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A hamburger in the shape of a Rubik’s cube, professional food photography',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    'A Man falling in Love with his Computer, digital art',
    'A photograph of a cyborg exploring Tokyo at night, lomography',
    'Dracula walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A Space Shuttle flying above Cape Town, digital art',
  ];

  export const artAiPrompts = [
    'A watercolor painting of a mermaid in a mystical underwater city',
    'A digital art piece of a futuristic cityscape at sunset',
    'An oil painting of a serene forest with glowing fireflies',
    'A surreal photo manipulation of a flying elephant',
    'A comic book-style illustration of a superhero battling a monster',
    'A portrait of a famous historical figure with a modern twist',
    'A 3D render of a futuristic spaceship exploring distant galaxies',
    'A mixed media artwork combining photography and collage',
    'A street art mural of an urban landscape with vibrant colors',
    'A digital collage of various animals morphed together',
    'A charcoal drawing of a dramatic stormy sky over a rocky coastline',
    'A psychedelic art piece inspired by the music of the 60s',
    'An abstract painting of a chaotic explosion of colors',
    'A photography series capturing the beauty of different seasons',
    'A fantasy illustration of a magical forest with mythical creatures',
    'A minimalist design of a famous landmark in a geometric style',
    'A watercolor portrait of a musician playing an instrument',
    'A digital art representation of a virtual reality world',
    'A surreal photo manipulation of a person floating in mid-air',
    'An oil painting of a majestic lion in a lush jungle setting',
    'A pop art-style illustration of a famous celebrity',
    'A mixed media artwork featuring vintage elements and modern technology',
    'A street art mural of a fantastical creature in an urban setting',
    'A digital collage of vintage photographs and modern objects',
    'A charcoal drawing of a dramatic city skyline at night',
    'A psychedelic art piece inspired by dreams and hallucinations',
    'An abstract painting of flowing patterns and shapes',
    'A photography series capturing the beauty of architecture',
    'A fantasy illustration of a mythical creature in a magical world',
    'A minimalist design of a famous painting with a modern twist',
    'A watercolor portrait of a dancer in motion',
    'A digital art representation of a futuristic cityscape',
    'A surreal photo manipulation of a person in a floating bubble',
    'An oil painting of a serene beach with palm trees',
    'A pop art-style illustration of a famous landmark',
    'A mixed media artwork combining traditional and digital techniques',
    'A street art mural of a political or social message',
    'A digital collage of nature elements and urban landscapes',
    'A charcoal drawing of a powerful thunderstorm',
    'A psychedelic art piece inspired by nature and spirituality',
    'An abstract painting of geometric shapes and patterns',
    'A photography series capturing the beauty of wildlife',
    'A fantasy illustration of a mythical creature in a dark forest',
    'A minimalist design of a famous movie poster',
    'A watercolor portrait of a child with a playful expression',
    'A digital art representation of an otherworldly landscape',
    'A surreal photo manipulation of a person with multiple reflections',
    'An oil painting of a serene mountain landscape',
    'A pop art-style illustration of a vintage advertisement',
    'A mixed media artwork exploring the theme of identity and self-expression',
  ];
  